version: '3'

services:
  game-server:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    restart: always

  frontend:
    build:
      context: ./frontend
    ports:
      - "4001:4001"
    depends_on:
      - game-server
