version: '3'

tasks:
  compose:
    desc: Docker compose backend and frontend services
    cmds:
      - docker compose down
      - docker compose up --build -d

  #
  # bot2 (python) tasks
  # 
  bot2:install:
    dir: bot2
    desc: Install bot2 dependencies
    cmds:
      - uv sync --dev

  bot2:lint:
    dir: bot2
    desc: Run bot2 linting with ruff
    cmds:
      - uv run ruff check --select I
      - uv run ruff check .
    deps:
      - bot2:install

  bot2:lint:fix:
    dir: bot2
    desc: Run bot2 linting with ruff and fix
    cmds:
      - uv run ruff check --select I --fix .
      - uv run ruff check . --fix
    deps:
      - bot2:install

  bot2:format:
    dir: bot2
    desc: Fix bot2 linting issues and format code
    cmds:
      - uv run ruff format .
    deps:
      - bot2:install

  bot2:format:check:
    dir: bot2
    desc: Check bot2 code formatting (no fix)
    cmds:
      - uv run ruff format --check .
    deps:
      - bot2:install

  bot2:typecheck:
    dir: bot2
    desc: Run bot2 type checking with ty
    cmds:
      - uv run ty check .
    deps:
      - bot2:install

  bot2:test:unit:
    dir: bot2
    desc: Run bot2 unit tests only (no server required)
    cmds:
      - uv run pytest tests/unit/ -v
    deps:
      - bot2:install

  bot2:test:integration:
    dir: bot2
    desc: Run bot2 integration tests (excluding slow tests, requires running server)
    cmds:
      - uv run pytest tests/integration/ -v
    deps:
      - bot2:install

  bot2:test:integration:fast:
    dir: bot2
    desc: Run bot2 integration tests (excluding slow tests, requires running server)
    cmds:
      - uv run pytest tests/integration/ -v -m "not slow"
    deps:
      - bot2:install

  bot2:test:integration:slow:
    dir: bot2
    desc: Run slow bot2 integration tests (requires running server)
    cmds:
      - uv run pytest tests/integration/ -v -m "slow"
    deps:
      - bot2:install

  bot2:test:all:
    dir: bot2
    desc: Run all bot2 tests (including slow tests,requires running server)
    cmds:
      - uv run pytest tests/ -v
    deps:
      - bot2:install

  bot2:check:
    dir: bot2
    desc: Run all bot2 checks (lint, format, typecheck, tests)
    deps:
      - bot2:lint
      - bot2:format
      - bot2:typecheck

  bot2:service:
    dir: bot2
    desc: Run the Bot Service
    cmds:
      - uv run python -m bot.service
    deps:
      - bot2:install

  bot2:service:dev:
    dir: bot2
    desc: Run the Bot Service with auto-reload for development
    cmds:
      - uv run uvicorn bot.service.bot_service:app --reload --host 0.0.0.0 --port 8080
    deps:
      - bot2:install

  #
  # backend (golang) tasks
  #
  be:build:
    dir: backend
    desc: Build the backend Go application
    cmds:
      - go build ./...

  be:test:
    dir: backend
    desc: Run backend unit tests
    cmds:
      - go test ./... -v

  be:test:short:
    dir: backend
    desc: Run backend unit tests (short mode)
    cmds:
      - go test ./... -short

  be:lint:
    dir: backend
    desc: Run backend linting with golangci-lint
    cmds:
      - golangci-lint run

  be:format:
    dir: backend
    desc: Format backend Go code
    cmds:
      - go fmt ./...

  be:format:check:
    dir: backend
    desc: Check backend Go code formatting (no fix)
    cmds:
      - test -z "$(gofmt -l .)"

  be:vet:
    dir: backend
    desc: Run go vet on backend code
    cmds:
      - go vet ./...

  be:tidy:
    dir: backend
    desc: Tidy backend Go modules
    cmds:
      - go mod tidy

  be:check:
    dir: backend
    desc: Run all backend checks (build, vet, test)
    cmds:
      - task: be:build
      - task: be:vet

  be:run:
    dir: backend
    desc: Run backend application
    cmds:
      - go run main.go

  #
  # kubernetes tasks
  #
  k8s:install-envsubst:
    desc: Install envsubst for Windows (required for k8s manifest templating)
    platforms: [windows]
    cmds:
      - go install github.com/a8m/envsubst/cmd/envsubst@latest
    status:
      - which envsubst

  k8s:install-kind:
    desc: Install kind (Kubernetes in Docker) for local cluster development
    cmds:
      - go install sigs.k8s.io/kind@latest
    status:
      - which kind